from .constants import *
import httpx
from httpx import HTTPError
from pydantic import BaseModel


# main function for processing the data and generate results. more strategies could be added here
def apply_strategy(strategy, nums):
    result = None
    strats = {
        "average": lambda nums: sum(nums) / len(nums),
        "sum": lambda nums: sum(nums),
        "max": lambda nums: max(nums),
        "min": lambda nums: min(nums),
    }

    strategy_function = strats.get(strategy, None)
    if strategy_function:
        result = strategy_function(nums)

    return result


# this class validates the received data from the external APIs
class APIResponse(BaseModel):
    oop_max: int
    stop_loss: int
    deductible: int


# generic function for invoking external API
def get_from_api(url):
    res = None
    try:
        res = httpx.get(url)
        res.raise_for_status()
        return res.json()
    except HTTPError as e:
        raise e
    except (httpx.RequestError, ValueError) as e:
        raise e


# this function collects data from the available external APIs, returns results generated by "apply strategy"
def process_data(member_id: int, strategy: str) -> APIResponse:
    response_fields = {}

    for url in API_URLS:
        try:
            res = get_from_api(f"{url}?member_id={member_id}")
            if res:
                response_body = APIResponse.model_validate(res)

                for key, value in response_body:
                    if key not in response_fields:
                        response_fields[key] = []

                    # response_fields stores the received data, organized by key, with a list of values
                    response_fields[key].append(value)
        except Exception as e:
            raise e

    return {key: apply_strategy(strategy, value) for key, value in response_fields.items()}
